# Generated by Django 6.0.7 on 2026-08-24 13:14

import apps.payments.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0015_alter_productattributevalue_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('first_name', models.CharField(max_length=20, verbose_name='نام گیرنده')),
                ('last_name', models.CharField(max_length=20, verbose_name='نام خانوادگی گیرنده')),
                ('address', models.CharField(blank=True, default='', max_length=256, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='کد پستی')),
                ('phone_number', models.CharField(blank=True, default='', max_length=24, verbose_name='تلفن')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='توضیحات')),
                ('order_date', models.DateField(default=datetime.datetime.today, verbose_name='تاریخ ثبت سفارش')),
                ('order_date_done', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل سفارش')),
                ('status', models.BooleanField(default=False, verbose_name='تایید سفارش')),
                ('payment_status', models.BooleanField(default=False, verbose_name='گزارش پرداخت')),
                ('total_price', models.PositiveIntegerField(null=True, verbose_name='قیمت نهایی')),
                ('receipt', models.ImageField(null=True, upload_to=apps.payments.models.sub_directory_path_receipt, verbose_name='تصویر رسید')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')),
                ('product_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت محصول')),
                ('product_off_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('description', models.CharField(max_length=256, verbose_name='توضیحات')),
                ('status', models.BooleanField(default=False, verbose_name='گزارش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='payments.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='catalogs.product')),
            ],
        ),
    ]
