# Generated by Django 6.0.7 on 2026-09-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Shopping cart'),
        ),
    ]
