# Generated by Django 6.0.7 on 2026-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0013_alter_productattributevalue_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='unit',
            field=models.CharField(blank=True, choices=[('gram', 'Gram'), ('kilogram', 'Kilogram'), ('گرم', 'گرم'), ('milliliter', 'Milliliter'), ('piece', 'Piece'), ('meter', 'Meter'), ('centimeter', 'Centimeter'), ('millimeter', 'Millimeter')], max_length=20, null=True, verbose_name='unit'),
        ),
    ]
