# Generated by Django 6.0.7 on 2026-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0014_alter_productattributevalue_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='unit',
            field=models.CharField(blank=True, choices=[('گرم', 'گرم'), ('کیلوگرم', 'کیلوگرم'), ('لیتر', 'لیتر'), ('میلی\u200cلیتر', 'میلی\u200cلیتر'), ('عدد', 'عدد'), ('متر', 'متر'), ('سانتی\u200cمتر', 'سانتی\u200cمتر'), ('میلی\u200cمتر', 'میلی\u200cمتر')], max_length=20, null=True, verbose_name='unit'),
        ),
    ]
